name: flutter_toolkit
description: Common code for my Flutter projects
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  shared_preferences: ^2.1.1
  auto_size_text: ^3.0.0
  sqflite: ^2.2.8+3
  firebase_core: ^2.12.0
  firebase_analytics: ^10.4.0
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  jiffy: ^6.1.0
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/images/
