name: flutter_toolkit
description: Common code for my Flutter projects
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  shared_preferences: any
  auto_size_text: ^3.0.0
  sqflite: ^2.0.2
  firebase_core: ^1.20.0
  firebase_analytics: ^9.3.0
  path_provider: ^2.0.9
  rxdart: ^0.27.5
  after_init: ^0.1.2
  jiffy: ^5.0.0
  quiver: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/images/
